---
# Source: gvds/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ht-config
data:
  APP_UID: "1000"
---
# Source: gvds/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ht-service
spec:
  selector:
    app: ht
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Source: gvds/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ht
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ht
  template:
    metadata:
      labels:
        app: ht
    spec:
      containers:
        - name: ht
          image: "ht-app:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_UID
              value: "1000"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
